# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29cd315a2b5b28249e02f064104a6e03b57797c8b0f3c580d0c40b53b4667d37e53789633901a38a3bfeebd8b6e6ae29eb03cd20d36691c0ff1da1f586862f26

test:
  secret_key_base: c420e64faa9f72ae47ad1e0609d6b191eef0e3f8ecb7f409a6ed396c6f0bfad021d03fda60a7bf700af858354b525f8095bcbf696c44b4b1ddb401aae878b001

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
